/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com;

/**
 *
 * @author mssrs
 */
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;
public class Moneytransfer extends javax.swing.JFrame {

    int count =0;
    public String str;
    public Moneytransfer() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("logo.png")));
    }
    public Moneytransfer(String s) {
        initComponents();
        str=s;
        accountno.setText("Your Account Number is : "+ str);
        setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        moneytransfer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        accountno = new javax.swing.JLabel();
        beneficiary = new javax.swing.JLabel();
        beneficiaryacc = new javax.swing.JTextField();
        amount = new javax.swing.JLabel();
        amounttb = new javax.swing.JTextField();
        transfer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        moneytransfer.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        moneytransfer.setText("Money Transfer");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/backbutton.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        accountno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        accountno.setForeground(new java.awt.Color(255, 0, 0));
        accountno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountno.setText("****");

        beneficiary.setText("Enter Beneficiary Account Number");

        beneficiaryacc.setForeground(new java.awt.Color(102, 102, 102));
        beneficiaryacc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                beneficiaryaccKeyTyped(evt);
            }
        });

        amount.setText("Enter Amount");

        amounttb.setForeground(new java.awt.Color(102, 102, 102));

        transfer.setText("Proceed and Transfer");
        transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(moneytransfer)
                .addGap(100, 100, 100))
            .addComponent(accountno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(beneficiary))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(amount)))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(amounttb, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(beneficiaryacc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(transfer)
                .addGap(212, 212, 212))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(moneytransfer)
                    .addComponent(jLabel1))
                .addGap(41, 41, 41)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accountno)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beneficiary)
                    .addComponent(beneficiaryacc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amounttb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amount))
                .addGap(66, 66, 66)
                .addComponent(transfer)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        new ManagemainJframe(str).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MousePressed

    private void beneficiaryaccKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_beneficiaryaccKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if(Character.isDigit(a)){ this.count++;
        if(this.count>10){
        beneficiaryacc.setText("");
        JOptionPane.showMessageDialog(null, "Account Number must be 10 digits");
        evt.consume();
        this.count=0;
        }
        }
        else {JOptionPane.showMessageDialog(null, "Account Number must be 10 digits"); evt.consume();}
    }//GEN-LAST:event_beneficiaryaccKeyTyped

    private void transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferActionPerformed
     try{
         int beneficiary_balance=0;
         int accountown_balance=0;
     Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","database","saketh6969");
     String sql ="SELECT BALANCE FROM THREETM WHERE ACCOUNTNO="+beneficiaryacc.getText();
     PreparedStatement pst = con.prepareCall(sql);
     ResultSet rs=pst.executeQuery();
     while(rs.next()){
     beneficiary_balance=rs.getInt(1);
     }
     
     String sql1="SELECT BALANCE FROM THREETM WHERE ACCOUNTNO="+str;
     PreparedStatement pst1 = con.prepareCall(sql1);
     ResultSet rs1=pst1.executeQuery();
     while(rs1.next()){
     accountown_balance=rs1.getInt(1);
     }
     int enteredamount=Integer.parseInt(amounttb.getText());
     if(enteredamount==0){
     accountno.setText("Entered amount must not be zero");
     }else{
     if(accountown_balance>=enteredamount && accountown_balance!=0){
         int finalbeneficiary = beneficiary_balance+enteredamount;
     String sql2 ="UPDATE THREETM SET BALANCE="+Integer.toString(finalbeneficiary)+" WHERE ACCOUNTNO="+beneficiaryacc.getText();
     PreparedStatement pst2 = con.prepareCall(sql2);
     pst2.executeUpdate(); 
     int finalowner=accountown_balance-enteredamount;
     String sql3 ="UPDATE THREETM SET BALANCE="+Integer.toString(finalowner)+" WHERE ACCOUNTNO="+str;
     PreparedStatement pst3 = con.prepareCall(sql3);
     pst3.executeUpdate(); 
     JOptionPane.showMessageDialog(null, "Money Transfer of "+amounttb.getText()+" is successful to account "+beneficiaryacc.getText());
     amounttb.setText("");
     beneficiaryacc.setText("");
     }else  accountno.setText("Insufficient funds");
     }
     }catch(Exception e){
       JOptionPane.showMessageDialog(null, e);
     }
    }//GEN-LAST:event_transferActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Moneytransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Moneytransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Moneytransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Moneytransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Moneytransfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountno;
    private javax.swing.JLabel amount;
    private javax.swing.JTextField amounttb;
    private javax.swing.JLabel beneficiary;
    private javax.swing.JTextField beneficiaryacc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel moneytransfer;
    private javax.swing.JButton transfer;
    // End of variables declaration//GEN-END:variables
}
